/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void reGenClicked(GButton source, GEvent event) { //_CODE_:reGen:684318:
  newPlot();
} 

public void numChange(GTextField source, GEvent event) { //_CODE_:newNum:295861:
  numPoints = int(newNum.getText());
} //_CODE_:newNum:295861:

public void noiseChange(GCheckbox source, GEvent event) { //_CODE_:noiseBox:905874:
  noise = noiseBox.isSelected();
} //_CODE_:noiseBox:905874:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  reGen = new GButton(this, 50, 740, 80, 30);
  reGen.setText("New Plot");
  reGen.setTextBold();
  reGen.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  reGen.addEventHandler(this, "reGenClicked");
  newNum = new GTextField(this, 150, 740, 160, 30, G4P.SCROLLBARS_NONE);
  newNum.setPromptText("Number of Points");
  newNum.setOpaque(true);
  newNum.addEventHandler(this, "numChange");
  noiseBox = new GCheckbox(this, 330, 740, 120, 30);
  noiseBox.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  noiseBox.setText("Noise-based point generation");
  noiseBox.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  noiseBox.setOpaque(true);
  noiseBox.addEventHandler(this, "noiseChange");
}

// Variable declarations 
// autogenerated do not edit
GButton reGen; 
GTextField newNum; 
GCheckbox noiseBox; 
